// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchConvertFiles(arg1, arg2) {
  return window['go']['gui']['App']['BatchConvertFiles'](arg1, arg2);
}

export function ConvertFile(arg1, arg2) {
  return window['go']['gui']['App']['ConvertFile'](arg1, arg2);
}

export function GetSupportedFormats() {
  return window['go']['gui']['App']['GetSupportedFormats']();
}
