// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchConvertFiles(arg1:Array<string>,arg2:string):Promise<void>;

export function ConvertFile(arg1:string,arg2:string):Promise<void>;

export function GetSupportedFormats():Promise<Array<string>>;
