// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchConvertFiles(arg1, arg2) {
  return window['go']['gui']['App']['BatchConvertFiles'](arg1, arg2);
}

export function CleanupTempFiles() {
  return window['go']['gui']['App']['CleanupTempFiles']();
}

export function CleanupTempInputFile(arg1) {
  return window['go']['gui']['App']['CleanupTempInputFile'](arg1);
}

export function ConvertFile(arg1, arg2) {
  return window['go']['gui']['App']['ConvertFile'](arg1, arg2);
}

export function ConvertFileWithPath(arg1, arg2, arg3) {
  return window['go']['gui']['App']['ConvertFileWithPath'](arg1, arg2, arg3);
}

export function DeleteTempFile(arg1) {
  return window['go']['gui']['App']['DeleteTempFile'](arg1);
}

export function GetFileInfo(arg1) {
  return window['go']['gui']['App']['GetFileInfo'](arg1);
}

export function GetSupportedFormats() {
  return window['go']['gui']['App']['GetSupportedFormats']();
}

export function OpenFile(arg1) {
  return window['go']['gui']['App']['OpenFile'](arg1);
}

export function SaveFileFromBytes(arg1, arg2) {
  return window['go']['gui']['App']['SaveFileFromBytes'](arg1, arg2);
}
