// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';

export function BatchConvertFiles(arg1:Array<string>,arg2:string):Promise<Array<gui.ConversionResult>>;

export function CleanupTempFiles():Promise<void>;

export function CleanupTempInputFile(arg1:string):Promise<void>;

export function ConvertFile(arg1:string,arg2:string):Promise<gui.ConversionResult>;

export function ConvertFileWithPath(arg1:string,arg2:string,arg3:string):Promise<gui.ConversionResult>;

export function DeleteTempFile(arg1:string):Promise<void>;

export function GetFileInfo(arg1:string):Promise<Record<string, any>>;

export function GetSavePath(arg1:string):Promise<string>;

export function GetSupportedFormats():Promise<Array<string>>;

export function OpenFile(arg1:string):Promise<void>;

export function SaveFileFromBytes(arg1:string,arg2:Array<number>):Promise<string>;
